name: janus_sip_client
description: This is a test project to test janus implementation in flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  web_socket_channel: ^2.4.0
  flutter_webrtc: ^0.9.26
  shared_preferences: ^2.1.0
  permission_handler: ^10.2.0
  crypto: ^3.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

# define launcher icon image
flutter_icons:
  android: true
  ios: true
  image_path: "images/maswerasei_icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/
