name: janus_sip_client
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  web_socket_channel: ^1.1.0
  flutter_webrtc: ^0.2.8
  shared_preferences: ^0.5.4+5
  permission_handler: ^5.0.0+hotfix.8
  flutter_country_picker: ^0.1.6
  flushbar: ^1.10.4
  dio: ^3.0.9
  grpc: ^2.1.3
  protobuf: ^1.0.1
  quiver: ^2.1.3
  contacts_service: ^0.4.6
  flutter_braintree: ^0.6.0
  fancy_bottom_navigation: ^0.3.2
  crypto: ^2.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

# define launcher icon image
flutter_icons:
  android: true
  ios: true
  image_path: "images/maswerasei_icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/
